### ISSUE TITLE
Does not support path parameter

### ISSUE THREAD

**Issue by mxr576** [drupol/phpcsfixer-configs-drupal#2]
If you try to provide a path parameter to PHPCS Fixer with this ruleset like this: `./vendor/bin/php-cs-fixer --config=../.php_cs.dist fix web/modules/contrib/color_field` then you see the following warning displayed by PHPCS fixer: `Paths from configuration file have been overridden by paths provided as command arguments.`. 

As a result, PHPCS Fixer only process `*.php` files (because this is what its default Finder whitelists) in the given directory and ignores any other Drupal specific files, like `*.module`.

**Comment by WengerK** [comment]
Think it's an issue from php-cs-fixer itself see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3044
I'll close, don't hesitate to re-open in case I misunderstand.
