### ISSUE TITLE
Add blank_line_after_start_of_class fixer

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupol/phpcsfixer-configs-drupal#7]
Original discussion: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3653#issuecomment-1366908645

With PHPCS Fixer 3.13.1, the blank line after class opening is removed and this is not a manageable behavior with PHPCS Fixer rules options.

I saw that this package is providing the rule to add a blank line at the end, could it also provides the rule to add the blank line at the start please?

Other packages provides this https://github.com/elyby/php-code-style#elyblank_line_around_class_body, but:
* then it is not compatible with `Drupal/blank_line_before_end_of_class` otherwise there will be 2 blank lines at the end.
* I would really prefer that this package becomes an "official" PHPCS Fixer reference for Drupal.

Until this rule is included in this package, I will use https://github.com/elyby/php-code-style and disable `Drupal/blank_line_before_end_of_class`.

**Comment by WengerK** [comment]
I openned a PR with a first attempt to fix this issue. 

It would be awesome if @FlorentTorregrosa and/or @drupol may have time to review and give feedbacks/tests on this contribution.

**Comment by drupol** [comment]
Hello,

It's been a few years since I last worked with Drupal, so I no longer devote my open-source efforts to it. Nonetheless, I have questions:

1. Is there a pre-existing php-cs-fixer rule that accomplishes what you aim to achieve with your implementation? It might be more sustainable in the long term if we can minimize the amount of custom code.
2. Are you aware of any person who could verify and provide feedback on the changes you're proposing?

Thank you!

**Comment by WengerK** [comment]
Thanks for your quick answer !
I fully understand your concern, here are my answers below. 

> Is there a pre-existing php-cs-fixer rule that accomplishes what you aim to achieve with your implementation? It might be more sustainable in the long term if we can minimize the amount of custom code.

From what I have read on https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3653#issuecomment-1366908645 it will not be supported by PHP-CS-Fixer by default (as it's a Drupal rule not a PHP/Symfony rule). 

Indeed another package seems to fix it https://github.com/elyby/php-code-style#elyblank_line_around_class_body but this package is not related to Drupal Fixer meaning it misses other Drupal Rules.

> Are you aware of any person who could verify and provide feedback on the changes you're proposing?

Myself and people at my organization ping @gido.
Maybe @FlorentTorregrosa who submits this initial issue and @sovetski who request new on the PHP-CS-Fixer thread.

**Comment by drupol** [comment]
Fair enough!

Let's have this PR reviewed by someone else, and once it's ok, we'll merge it.

Thanks for using this package... honestly I never though it was still used!

**Comment by FlorentTorregrosa** [comment]
Hi,

Thanks @WengerK for the PR, tested ok for me.

@drupol, thanks for your repositories! I use them in my skeleton, so on a lot of projects.

**Comment by drupol** [comment]
Excellent :)
